version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
